# -*- coding: utf-8 -*-

from .losses import (
    bernoulli_entropy,
    entropy_regularized_qubo_loss,
    qubo_expected_energy_loss,
)
from .benchmarks import (
    MaxCutBenchmark,
    PlantedParityQUBOBenchmark,
    make_planted_bipartite_maxcut,
    make_planted_parity_qubo,
    make_random_maxcut,
    make_random_qubo,
    maxcut_qubo_from_edges,
)
from .heuristics import (
    batch_greedy_local_search,
    best_of_random,
    greedy_local_search,
    greedy_round_from_probabilities,
    simulated_annealing,
)
from .qaoa_init import (
    calibrate_probabilities_with_assignment,
    probabilities_from_qaoa_ry_angles,
    qaoa_ry_angles_from_probabilities,
)
from .preprocess import (
    componentwise_qaoa_resource_summary,
    isolated_variable_fixing,
    qubo_component_subproblems,
    qubo_connected_components,
    reduce_by_fixing_isolated_variables,
    residual_qaoa_active_summary,
)
from .qaoa_limits import (
    max_statevector_qubits,
    qaoa_resource_summary,
    qaoa_two_qubit_gate_count,
    statevector_memory_bytes,
)
from .qaoa_statevector import (
    optimize_qaoa_statevector,
    product_state_from_probabilities,
    qaoa_expected_energy,
    qaoa_state,
    qubo_energy_vector,
)
from .qubo import (
    EDGE_FEATURE_DIM,
    NODE_FEATURE_DIM,
    QUANTUM_NODE_FEATURE_DIM,
    QUBOProblem,
)
from .qubo_sqnn import (
    EdgeConditionedRotation,
    QUBOQuantumDataWarmStartSQNN,
    QuantumDataBlochInitializer,
    QuantumDataRotationEncoder,
    QUBOHybridWarmStartSQNN,
    QUBOInstanceEmbeddingWarmStartSQNN,
    QUBOMeanFieldWarmStart,
    QUBONodeOnlySQNN,
    QUBOPositiveXSynchronousLocalFieldSQNN,
    QUBOSymmetricWarmStartSQNN,
    QUBOSynchronousLocalFieldSQNN,
    QUBOWarmStartSQNN,
    bloch_to_probabilities,
    probabilities_to_bloch,
)
from .sampling import (
    best_sample_from_probabilities,
    sample_bernoulli,
    sample_qubo_solutions,
)

__all__ = [
    "EDGE_FEATURE_DIM",
    "NODE_FEATURE_DIM",
    "QUANTUM_NODE_FEATURE_DIM",
    "EdgeConditionedRotation",
    "MaxCutBenchmark",
    "PlantedParityQUBOBenchmark",
    "QUBOHybridWarmStartSQNN",
    "QUBOInstanceEmbeddingWarmStartSQNN",
    "QUBOMeanFieldWarmStart",
    "QUBONodeOnlySQNN",
    "QUBOPositiveXSynchronousLocalFieldSQNN",
    "QUBOProblem",
    "QUBOQuantumDataWarmStartSQNN",
    "QUBOSymmetricWarmStartSQNN",
    "QUBOSynchronousLocalFieldSQNN",
    "QUBOWarmStartSQNN",
    "QuantumDataBlochInitializer",
    "QuantumDataRotationEncoder",
    "batch_greedy_local_search",
    "bernoulli_entropy",
    "best_of_random",
    "best_sample_from_probabilities",
    "bloch_to_probabilities",
    "calibrate_probabilities_with_assignment",
    "componentwise_qaoa_resource_summary",
    "entropy_regularized_qubo_loss",
    "greedy_local_search",
    "greedy_round_from_probabilities",
    "isolated_variable_fixing",
    "make_planted_bipartite_maxcut",
    "make_planted_parity_qubo",
    "make_random_maxcut",
    "make_random_qubo",
    "max_statevector_qubits",
    "maxcut_qubo_from_edges",
    "probabilities_from_qaoa_ry_angles",
    "probabilities_to_bloch",
    "product_state_from_probabilities",
    "qaoa_expected_energy",
    "qaoa_resource_summary",
    "qaoa_ry_angles_from_probabilities",
    "qaoa_state",
    "qaoa_two_qubit_gate_count",
    "qubo_component_subproblems",
    "qubo_connected_components",
    "qubo_expected_energy_loss",
    "qubo_energy_vector",
    "optimize_qaoa_statevector",
    "reduce_by_fixing_isolated_variables",
    "residual_qaoa_active_summary",
    "sample_bernoulli",
    "sample_qubo_solutions",
    "simulated_annealing",
    "statevector_memory_bytes",
]
